services:

  mysql:
    image: mysql:latest
    container_name: rebit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LANG: ko_KR.UTF-8 # client의 default값이 latin1 대신 utf8mb4
      TZ: Asia/Seoul
    command:
      [
        "--lower_case_table_names=1",
        "--max_connections=2048",
        "--wait_timeout=3600"
      ]
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - rebit
    restart: always

  redis:
    image: redis:latest
    container_name: rebit-redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./db/redis:/data
    networks:
      - rebit
    restart: always

  backend:
    image: audejr123/rebit:latest
    env_file:
      - .env
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    volumes: # spring log file[/rebit/log/server.log] - connect to docker container[/app/application.log]
      - ~/rebit/log/server.log:/app/application.log
    depends_on:
      - mysql
      - redis
    networks:
      - rebit

  nginx:
    image: nginx:1.24.0
    container_name: rebit-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/home/rebit/log
      - ./nginx/ssl:/etc/letsencrypt
    environment:
      TZ: Asia/Seoul
    depends_on:
      - backend
    networks:
      - rebit
    restart: always

networks:
  rebit:
    external: true
