spring:
  application:
    name: rebit

  datasource: # 데이터베이스 연결을 위한 설정
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:rebit}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # 데이터베이스 문법(방언) 설정
    open-in-view: false # 트랜잭션이 종료된 후 연결을 유지하지 않도록 설정
    defer-datasource-initialization: true # data.sql 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션

  sql:
    init:
      data-locations: classpath:data.sql  # 초기 데이터 설정

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# 카카오 소셜 로그인을 위해 사용하는 정보들 설정
oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID:test-client-id}
    url:
      auth-url: ${OAUTH_KAKAO_AUTH_URL:kakao-auth-url}
      api-url: ${OAUTH_KAKAO_API_URL:kakao-api-url}
      redirect-url: ${OAUTH_KAKAO_REDIRECT_URI:kakao-redirect-url}
      logout-url-template: ${OAUTH_KAKAO_LOGOUT_URL_TEMPLATE:kakao-logout-url-template}

custom:
  jwt:  # Jwt 시크릿 키 설정
    secretKey: ${JWT_SECRET_KEY:dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleS10ZXN0LXNlY3JldC1rZXktdGVzdC1zZWNyZXQta2V5}
  aladin: # 알라딘 API 키 설정
    ttb-key: ${TTB_KEY:test-ttb-key}

logging:
  level:
    org.springframework:
      transaction.interceptor: trace    # 트랜잭션 로그 설정

    p6spy: info # p6spy 로그 레벨 설정

  file: # 로그 파일 설정
    name: /app/application.log

# p6spy 로그 여부 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

# AWS S3 설정
cloud:
  aws:
    credentials: # IAM으로 생성한 키 정보 입력
      access-key: ${S3_ACCESS_KEY:test-access-key}
      secret-key: ${S3_SECRET_KEY:test-secret-key}
    S3:
      bucket: ${S3_BUCKET_NAME:test-bucket} # 버켓 이름 설정
    region:
      static: ${S3_REGION:ap-northeast-2} # 버켓이 위치한 region 설정
    stack:
      auto: false # 자동 스택 생성 기능 사용 여부

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never   # 필요시 always로 변경

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

